config/routes.rb
Rails.application.routes.draw do
  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)
   
  resources :categories

  devise_for :users
  resources :projects 
  #   resources :comments

    resources :projects do
    resources :members

	 resources :comments do
    resources :replies
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
   end
   end
  
  root 'projects#index'
  # get 'member'=>'projects#member'
 
end

app/models/comment.rb
class Comment < ApplicationRecord
   belongs_to :project
   has_many :replies, dependent: :destroy
    mount_uploader :image, ImageUploader
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController

	def create

    @project= Project.find(params[:project_id])
    @comment = @project.comments.create(comment_params)
    redirect_to project_path(@project)
     # render 'projects/create_comments'
      # render 'projects/create_comments'
  end

  def edit
     @blog = Project.find(params[:project_id])
     @comment = Comment.find(params[:id])
  end

 def destroy
    #@article = Article.find(params[:id])
    #@comment = @article.comments.find(params[:article_id])
    @blog = Project.find(params[:project_id])
     @comment = Comment.find(params[:id])
    @comment.destroy
    # redirect_to project_path(@project)
     redirect_to @blog

  end

  def update
     @blog = Project.find(params[:project_id])
     @comment = Comment.find(params[:id])
     @comment.update(comment_params)
      flash[:notice] = "Comment Updated"

   redirect_to blog_path(@blog)
     
  end
  private
    def comment_params
      params.require(:comment).permit(:commenter, :body, :image)
    end

end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/views/comments/_comments.html.erb
<div class="container">
<%@project.comments.each do |comment|%> 
<p>
  <strong>Commenter:</strong>
  <%= comment.commenter %>
</p>
 
<p>
  <strong>Comment:</strong>
  <%= comment.body %>
</p>
<p>
 <strong>image:</strong>
    <%=image_tag comment.image,:class=>"img-responsive",:height=>"150", :width=>"150" %>
  </p>
  <p>
 
<p>
  <%= link_to 'Destroy Comment', [comment.project, comment],
               method: :delete,
               data: { confirm: 'Are you sure?' } %>
</p>
<p>
  <%= link_to 'Edit Comment', edit_project_comment_path(comment.project, comment) %>
</p>

<h2> reply a comment</h2>
<% @replies=Reply.where(:comment_id=> comment.id)
%>
<div class="Replies-container_<%= comment.id%>">

<%= render 'replies/Replie'%>
 </div>
<%= render 'replies/form', :comment=>comment %>
<%end%>
</div>

app/views/comments/_form.html.erb
<%= form_for([@project, @project.comments.build],:remote => true) do |f| %>
 
<div style="margin-bottom: 25px"class="form-group">
        <label class="col-md-4 control-label">commenter</label>
        <div class="col-md-6  inputGroupContainer">
          <div class="input-group"> <span class="input-group-addon"><i class="glyphicon glyphicon-user"></i></span>
          <%= f.text_field :commenter,:placeholder=>"commenter",:class=>"form-control" %></br>
          </div>
        </div>
      </div>
     </br></br>

   <div style="margin-bottom: 25px"class="form-group">
        <label class="col-md-4 control-label">body</label>
        <div class="col-md-6  inputGroupContainer">
          <div class="input-group"> <span class="input-group-addon"><i class="glyphicon glyphicon-comment"></i></span>
          <%= f.text_field :body,:placeholder=>"comment here",:class=>"form-control" %></br>
          </div>
        </div>
      </div>
     </br></br>
  
  <div class="form-group">
        <label class="col-md-4 control-label">Document</label>
        <div class="col-md-6  inputGroupContainer">
          <div class="input-group"> <span class="input-group-addon"><i class="glyphicon glyphicon-paperclip"></i></span>
          <%= f.file_field :image,:class=>"form-control",:class=>"img-rounded" %></br>
          </div>
        </div>
      </div>
     </br></br>
  
   <div class="form-group">
        <label class="col-md-4 control-label"></label>
        <div class="col-md-6  inputGroupContainer">
         <%= f.submit :class=>"btn btn-success" %>
          </div>
        </div>
   <p>
   <%= hidden_field_tag :authenticity_token, form_authenticity_token %>
  </p>
<% end %>

app/views/comments/create_Replies.js.erb
$('.Replies-container_<%= params[:reply][:comment_id] %>').html('<%= escape_javascript( render "replies/Replie")%>')
// $("#reply_body")[0].reset();

app/views/comments/edit.html.erb
<h3>Edit tg67hy8nupl.;</h3>


<%= form_for([@project, @comment] , :method =>"patch" ) do |f| %>
<%#= form_for(:comment, url: "/blogs/#{@blog.id}/comments/#{@comment.id}/edit") do |f| %>

  <p>
    <%= f.label :commenter %><br>
    <%= f.text_field :commenter %>
  </p>
  <p>
    <%= f.label :body %><br>
    <%= f.text_area :body %>
  </p>
  <p>
    <%= f.submit %>
  </p>
<% end %>