config/routes.rb
Rails.application.routes.draw do
  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)
   
  resources :categories

  devise_for :users
  resources :projects 
  #   resources :comments

    resources :projects do
    resources :members

	 resources :comments do
    resources :replies
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
   end
   end
  
  root 'projects#index'
  # get 'member'=>'projects#member'
 
end

app/models/project.rb
class Project < ApplicationRecord
  mount_uploader :document, ImageUploader
  has_many :comments, dependent: :destroy
  belongs_to :category
  has_many :members
  has_many  :users
  
end

app/controllers/projects_controller.rb
class ProjectsController < ApplicationController
  # skip_before_filter :verify_authenticity_token
  # protect_from_forgery prepend: true, with: :exception
 before_action :authenticate_user!
 # before_action :set_bug, only: [:show, :edit, :update]
  before_action :set_project, only: [:show, :edit, :update, :destroy]

  # GET /projects
  # GET /projects.json
 def index


  @member = Member.where(:user_id => current_user.id) 
  # @member.each do |member| 
  #   @projects = Project.where(:id => member.project_id)
       if params[:search].present?
         @projects = Project.where('name LIKE ? AND ractive=?', "%#{params[:search]}%",true)

      elsif params[:category].present?
           category=Category.find(params[:category])
           @projects = category.projects.where('name LIKE ? AND ractive=? ', "%#{params[:search]}%",true)
      else
        @projects = Project.where(:ractive=>'true')
     end
  end 

  # GET /projects/1
  # GET /projects/1.json
  def show

  end

  # GET /projects/new
  def new
    @project = Project.new
  end

  # GET /projects/1/edit
  def edit
  end

  # POST /projects
  # POST /projects.json
  def create
    @project = Project.new(project_params)

    respond_to do |format|
      if @project.save
        format.html { redirect_to @project, notice: 'Project was successfully created.' }
        format.json { render :show, status: :created, location: @project }
      else
        format.html { render :new }
        format.json { render json: @project.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /projects/1
  # PATCH/PUT /projects/1.json
  def update
    respond_to do |format|
      if @project.update(project_params)
        format.html { redirect_to @project, notice: 'Project was successfully updated.' }
        format.json { render :show, status: :ok, location: @project }
      else
        format.html { render :edit }
        format.json { render json: @project.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /projects/1
  # DELETE /projects/1.json
  def destroy
    @project.destroy
    respond_to do |format|
      format.html { redirect_to projects_url, notice: 'Project was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_project
      @project = Project.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def project_params
      params.require(:project).permit(:name, :document, :image, :category_id,:status,:ractive)
    end
end

app/helpers/projects_helper.rb
module ProjectsHelper
end

app/views/projects/_form.html.erb
<%= form_for(project) do |f| %>
  <% if project.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(project.errors.count, "error") %> prohibited this project from being saved:</h2>

      <ul>
      <% project.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

    <div style="margin-bottom: 25px"class="form-group">
        <label class="col-md-4 control-label">First Name</label>
        <div class="col-md-6  inputGroupContainer">
          <div class="input-group"> <span class="input-group-addon"><i class="glyphicon glyphicon-user"></i></span>
          <%= f.text_field :name,:placeholder=>"Name",:class=>"form-control" %></br>
          </div>
        </div>
      </div>
     </br></br>

<div class="form-group">
        <label class="col-md-4 control-label">Document</label>
        <div class="col-md-6  inputGroupContainer">
          <div class="input-group"> <span class="input-group-addon"><i class="glyphicon glyphicon-paperclip"></i></span>
          <%= f.file_field :document,:class=>"form-control" %></br>
          </div>
        </div>
      </div>
     </br></br>
 

   <div class="form-group">
        <label class="col-md-4 control-label">select category</label>
        <div class="col-md-6  inputGroupContainer">
          <div class="input-group"> <span class="input-group-addon"><i class="glyphicon glyphicon-list"></i></span>
  <%= f.select(:category_id, Category.all.collect {|u| [u.name, u.id]},:prompt => 'Select Category') %>
          </div>
        </div>
      </div>
      </br></br>

       <div class="form-group">
        <label class="col-md-4 control-label">select status</label>
        <div class="col-md-6  inputGroupContainer">
          <div class="input-group"> <span class="input-group-addon"><i class="glyphicon glyphicon-list"></i></span>
       <%=f.select "status", options_for_select([ "Available", "pending" ,"complete"], "complete"),:prompt => 'Select Status'%>
          </div>
        </div>
      </div>
     </br></br>

      <div class="form-group">
        <label class="col-md-4 control-label">ractive</label>
        <div class="col-md-6  inputGroupContainer">     
     <%= f.label :ractive %><br/>
     <%= f.label :ractive, "Yes", :value => "true"  %>
     <%= f.radio_button :ractive, true ,:checked=>true%>
     <%= f.label :ractive, "No", :value => "false" %>
    <%= f.radio_button :ractive, false, :checked => true %> 
       </div>
        </div>
        </br></br>
    
 
          <div class="form-group">
        <label class="col-md-4 control-label"></label>
        <div class="col-md-6  inputGroupContainer">
         <%= f.submit :class=>"btn btn-success" %>
          </div>
        </div>
        </br></br>
     <% end %>
<script type="text/javascript">
 
   $(document).ready(function() {
    $('#new_project').bootstrapValidator({
        // To use feedback icons, ensure that you use Bootstrap v3.1.0 or later
        feedbackIcons: {
            valid: 'glyphicon glyphicon-ok',
            invalid: 'glyphicon glyphicon-remove',
            validating: 'glyphicon glyphicon-refresh'
        },
        fields: {
            "project[name]": {
                validators: {
                        stringLength: {
                        min: 2,
                    },
                        notEmpty: {
                        message: 'Please supply your name'
                    }
                }
            },
             "project[document]": {
                validators: {
                     stringLength: {
                        min: 2,
                    },
                    notEmpty: {
                        message: 'Please select document'
                    }
                }
            },
           
           "project[category_id]": {
                validators: {
                    notEmpty: {
                        message: 'Please select your category'
                    }
                }
            },
            "project[status]": {
                validators: {
                    notEmpty: {
                        message: 'Please select your status'
                    }
                }
            },
            "project[ractive]": {
                validators: {
                     stringLength: {
                        min: 4,
                    },
                    notEmpty: {
                        message: 'Please select active'
                    }
                }
            }
            
                       
            
            
            }
        })
    
  
        .on('success.form.bv', function(e) {
            $('#new_project').slideDown({ opacity: "show" }, "slow") // Do something ...
                $('#reg_form').data('bootstrapValidator').resetForm();
 
            // Prevent form submission
            e.preventDefault();
 
            // Get the form instance
            var $form = $(e.target);
 
            // Get the BootstrapValidator instance
            var bv = $form.data('bootstrapValidator');
 
            // Use Ajax to submit form data
            $.post($form.attr('action'), $form.serialize(), function(result) {
                console.log(result);
            }, 'json');
        });
});
 
</script>

app/views/projects/create_comments.js.erb
$('.comments-container').html('<%= escape_javascript( render "comments/comments")%>')
$("#new_comment")[0].reset();
$("#new_comment").hide();

app/views/projects/edit.html.erb
<h1>Editing Project</h1>

<%= render 'form', project: @project %>

<%= link_to 'Show', @project %> |
<%= link_to 'Back', projects_path %>

app/views/projects/index.html.erb
<div class="container">
<p id="notice"><%= notice %></p>
<% if params[:search].present? || params[:category].present?%>
   <%= @projects.count %> Results found
  
  <% end %>
<h1>Projects</h1>

<table class="table table-bordered">
  <thead>
    <tr>
      <th>Name</th>
      <th>status</th>
      <th>Document</th>
       <th>category</th>
      <th>email_id</th>
      <th colspan="3"></th>

    </tr>
  </thead>

  <tbody>
     <tr>
    <% @projects.each do |project| %>
  
      <tr>
        <td><%= project.name %></td>
         <td><%= project.status%></td>

         <% if project.document.present? %> 
        <td> <%= project.document.file.original_filename %></td>
          <%end%>

        <% if project.category_id.present? %> 
     <td><%=Category.find(project.category_id).name %></td>
         <%end%>

        <td> <%= project.members.collect(&:user).compact.flatten.collect(&:email) %> </td>
        
    
        
          
        <td><%= link_to 'Show', project ,:class=>"btn btn-success"%></td>
        <td><%= link_to 'Edit', edit_project_path(project),:class=>"btn btn-primary disabled" %></td>
      <td><%= link_to 'Destroy', project, method: :delete, data: { confirm: 'Are you sure?' },:class=>"btn btn-danger" %></td>

      </tr>
     
    <% end %>
    
  </tbody>
</table>

</div>

app/views/projects/new.html.erb
<h1>New Project</h1>

<%= render 'form', project: @project %>

<div class="form-group">
        <label class="col-md-4 control-label"></label>
        <div class="col-md-6  inputGroupContainer">
        <%= link_to 'Back', categories_path,:class=>"btn btn-success btn_sm" %>   
          </div>
        </div>

app/views/projects/show.html.erb
<div class ="container">
<p id="notice"><%= notice %></p>
<% if params[:search].present? %>
   <%= @projects.count %> Results found.
   <% else %>
   no result found
  <% end %>
<p>
  <strong>Name:</strong>
  <%= @project.name %>
</p>
      
<p>
    <%= link_to 'member', new_project_member_path(@project) ,:class => "btn btn-primary"%>
</p>
     
</p>
  <strong>document:</strong>
<% if @project.document.present? %>
<a href="<%=@project.document.url %>"><%= @project.document.file.original_filename %></a>
  <% end %>
 </p>

<h2>Comments</h2>
    <div class="comments-container">
    <%= render 'comments/comments' %>
    </div>
       <h2>Add a comment:</h2>
      <%#if  Comment.where(:blog_id => @blog.id, user_id: current_user.id).present?
       %>
     <%= render 'comments/form'%>

<%= link_to 'Edit', edit_project_path(@project) %> |
<%= link_to 'Back', projects_path %>
</div>