config/routes.rb
Rails.application.routes.draw do
  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)
   
  resources :categories

  devise_for :users
  resources :projects 
  #   resources :comments

    resources :projects do
    resources :members

	 resources :comments do
    resources :replies
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
   end
   end
  
  root 'projects#index'
  # get 'member'=>'projects#member'
 
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Blog6</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
  <nav class="navbar navbar-inverse">
      <div class="container">
        <div class="navbar-header">
          <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar" aria-expanded="false" aria-controls="navbar">
            <span class="sr-only">Toggle navigation</span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
          </button>
          <a class="navbar-brand" href="#">Project name</a>
        </div>

        <div id="navbar" class="navbar-collapse collapse" aria-expanded="false" style="height: 1px;">
          <ul class="nav navbar-nav">
            <li class="active"><%= link_to 'Home', projects_path %></li>
             <li><%= link_to 'New Project', new_project_path %></li>
              <li><%=link_to 'Category',categories_path%></li>
              <% unless user_signed_in? %>
            <li><a href="/users/sign_in">Login</a></li>
            <li><a href="/users/sign_up">Register</a></li>
            <% else %>
               <li><%= link_to "Sign out", destroy_user_session_path, :method => :delete %></li>
                <%end%>

            
              
            <!-- <li class="dropdown">
              <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">Dropdown <span class="caret"></span></a>
              <ul class="dropdown-menu">
                <li><a href="#">Action</a></li>
                <li><a href="#">Another action</a></li>
                <li><a href="#">Something else here</a></li>
                <li role="separator" class="divider"></li>
                <li class="dropdown-header">Nav header</li>
                <li><a href="#">Separated link</a></li>
                <li><a href="#">One more separated link</a></li>
              </ul> -->
            </li>
          </ul>
          <ul class="nav navbar-nav navbar-right">
           <%=form_tag "/projects" ,:method=>"GET" do %>

      <%= text_field_tag :search, params[:search] , :placeholder => "Type here to search"%>
      <%= select_tag "category", options_from_collection_for_select(Category.all, 'id', 'name'),:prompt=>'select category'%>  
      <%= submit_tag "Search", :class=>"btn btn-success btn-xs"%>
     <%end%>
    </div>
            
          </ul>

        </div><!--/.nav-collapse -->
      </div>
     </nav>
 
<br>

    <%= yield %>
  </body>
</html>

<script src='http://cdnjs.cloudflare.com/ajax/libs/bootstrap-validator/0.4.5/js/bootstrapvalidator.min.js'></script>